version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=eshop
  nginx:
    depends_on: 
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
      - "8080:8080"
  api:
    depends_on:
      - postgresdb
    build: 
      dockerfile: Dockerfile
      context: ./BE
    volumes:
      - /app/node_modules
      - ./BE:/app
    environment:
      -  DB_HOST=postgresdb
      -  DB_USERNAME=postgres
      -  DB_PASSWORD=123456
      -  DB_NAME=eshop
  client:
    stdin_open : true
    volumes:
      - /app/node_modules
      - ./FE:/app
    build:
      context: ./FE
      dockerfile: Dockerfile
    
